### ISSUE TITLE
Aberrant folder hierarchy 

### ISSUE THREAD

**Issue by PascaldeBoer** [rijksuniversiteit-groningen/iBridges-Gui#14]
In many cases using dots (.) in subfolder names is desired or even created as output by analytical machines. If complete folders which contain subfolders with dots in the name, from the 3rd level on, are uploaded to the RDMS, new subfolders with the dot in the name are created 1 level up in the RDMS collection. See picture.

![smFRET_folderTransfer_error](https://user-images.githubusercontent.com/107916721/180239005-2f9aacd6-87ab-43e4-9fc2-fb99cc9acce5.jpg)
The complete folder that I uploaded here was (1) 20220307_smFRET_Marco. The folder contains basically 3 levels, (1) the head folder of one day experiments, (2) one specific measurement, with a specific condition also containing a third level folder (3) .ipynb_checkpoints. When this folder is uploaded to the RDMS via iBridges a new folder for the .ipynb_checkpoint is created in the iRODS collection in the second level with the name e.g. for specific condition 50HEPES600KCl120MgATTP100GB20VO4\.ipynb_checkpoints. The .ipynb_checkpoints folders are removed from the respective conditional subfolders in the collection.

Importantly, this only seem to happen when the subfolders with a dot in the name are in the 3rd or higher level. It works fine when the subfolders are in the second layer. See next picture:

![Subfolder_hierarchy_error](https://user-images.githubusercontent.com/107916721/180241198-e7ec7a58-02f0-447a-9203-215f5d1be595.jpg)
The normal situation I already uploaded to the RDMS via iBridges and is called varian_agilent (indicated with 'Normal'). You can see dat the folders with the .fid in the name are normally organized in the second layer of the collection within the RDMS. For testing I put the varian_agilent folder in a new head folder called Test_folder_hierarchy, which put the .fid folders in the 3rd level instead of the 2nd. When this Test_folder_hierarchy collection is uploaded to the RDMS via iBridges, again the collection in iRODS becomes re-organized putting the .fid folders in the 2nd level and calling them varian_agilent\quinine_gHSQC.fid e.g. 

I discovered this issue, when I wanted to download a respective collections from the RDMS, which did not work with the error:
```

[2022-07-21 10:55:08,777] {irodsConnector.py:493} INFO - INFO: Downloading /testrug/home/pascal.de.boer@rug.nl/iBridges_test/20211208_Lefebvre/strep-test/Neu-strep-test_MMStack_Default.ome.tif/DisplaySettings.json to C:/Users/P265301/Downloads\20211208_Lefebvre\strep-test\Neu-strep-test_MMStack_Default.ome.tif\DisplaySettings.json
[2022-07-21 10:55:08,784] {irodsConnector.py:496} INFO - DOWNLOAD ERROR
Traceback (most recent call last):
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\manager\collection_manager.py", line 17, in get
    result = query.one()
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\query.py", line 224, in one
    raise NoResultFound()
irods.exception.NoResultFound

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\P265301\Documents\GitHub\iBridges\utils\irodsConnector.py", line 494, in downloadData
    self.session.data_objects.get(sourcePath, local_path=destPath, **options)
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\manager\data_object_manager.py", line 87, in get
    parent = self.sess.collections.get(irods_dirname(path))
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\manager\collection_manager.py", line 19, in get
    raise CollectionDoesNotExist()
irods.exception.CollectionDoesNotExist
[2022-07-21 10:55:08,890] {dataTransfer.py:260} INFO - CollectionDoesNotExist()
[2022-07-21 10:55:32,567] {dataTransfer.py:255} INFO - UpDownload Diff: ([], [], ['_1/_1_MMStack_Default.ome.tif', 'strep-test/Neu-strep-test_MMStack_Default.ome.tif/DisplaySettings.json', '_1/DisplaySettings.json', 'strep-test/Neu-strep-test_MMStack_Default.ome.tif/Neu-strep-test_MMStack_Default.ome.tif_MMStack_Default_metadata.txt', 'strep-test/comments.txt', 'strep-test/strep-test_MMStack_Default.ome.tif', '_1/comments.txt', 'strep-test/laser profile.tif', 'strep-test/DisplaySettings.json', 'strep-test/Neu-strep-test_MMStack_Default.ome.tif/comments.txt', 'strep-test/strep-test_MMStack_Default_metadata.txt', 'strep-test/Neu-strep-test_MMStack_Default.ome.tif/Neu-strep-test_MMStack_Default.ome.tif_MMStack_Default.ome.tif'], [])
[2022-07-21 10:55:32,569] {irodsConnector.py:419} INFO - iRODS DOWNLOAD: <iRODSCollection 12160047 b'20211208_Lefebvre'>-->C:/Users/P265301/Downloads
[2022-07-21 10:55:32,589] {irodsConnector.py:480} INFO - IRODS DOWNLOAD started:
[2022-07-21 10:55:32,591] {irodsConnector.py:493} INFO - INFO: Downloading /testrug/home/pascal.de.boer@rug.nl/iBridges_test/20211208_Lefebvre/_1/_1_MMStack_Default.ome.tif to C:/Users/P265301/Downloads\20211208_Lefebvre\_1\_1_MMStack_Default.ome.tif
[2022-07-21 10:55:32,771] {parallel.py:307} INFO - num_threads = 3 ; (P)artitionSize = 177862361
[2022-07-21 10:56:20,295] {irodsConnector.py:493} INFO - INFO: Downloading /testrug/home/pascal.de.boer@rug.nl/iBridges_test/20211208_Lefebvre/strep-test/Neu-strep-test_MMStack_Default.ome.tif/DisplaySettings.json to C:/Users/P265301/Downloads\20211208_Lefebvre\strep-test\Neu-strep-test_MMStack_Default.ome.tif\DisplaySettings.json
[2022-07-21 10:56:20,299] {irodsConnector.py:496} INFO - DOWNLOAD ERROR
Traceback (most recent call last):
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\manager\collection_manager.py", line 17, in get
    result = query.one()
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\query.py", line 224, in one
    raise NoResultFound()
irods.exception.NoResultFound

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\P265301\Documents\GitHub\iBridges\utils\irodsConnector.py", line 494, in downloadData
    self.session.data_objects.get(sourcePath, local_path=destPath, **options)
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\manager\data_object_manager.py", line 87, in get
    parent = self.sess.collections.get(irods_dirname(path))
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\manager\collection_manager.py", line 19, in get
    raise CollectionDoesNotExist()
irods.exception.CollectionDoesNotExist
[2022-07-21 10:56:20,302] {dataTransfer.py:260} INFO - CollectionDoesNotExist()
```

Notably this only happened to me on a windows 10 laptop running iBridges with the python API. Jelte tried similar things on his linux machine also only with the python API, but the described issues did not occur with him. 

I both tried via the develop and jpm/feature/resource_space_checking branches from Github

This is my configuration for iRODS:

```
{
    "irods_authentication_scheme": "PAM",
    "irods_client_server_negotiation": "request_server_negotiation",
    "irods_client_server_policy": "CS_NEG_REQUIRE",
    "irods_default_resource": "rootResc",
    "irods_encryption_algorithm": "AES-256-CBC",
    "irods_encryption_key_size": 32,
    "irods_encryption_num_hash_rounds": 16,
    "irods_encryption_salt_size": 8,
    "irods_host": "rdms-test-icat.data.rug.nl",
    "irods_port": 1247,
    "irods_ssl_verify_server": "cert",
    "irods_user_name": "pascal.de.boer@rug.nl",
    "irods_zone_name": "testrug",
    "ui_tabs": [
		"tabBrowser",
		"tabUpDownload",
		"tabELNData",
		"tabDataCompression"
	]
}
```

**Comment by jnimoth** [comment]
Is there any progress on this issue or more input? I think it is quite important to take a look at this, especially if it does appear when the program is used under Windows as it is suggested by Pascal and my trials. As he said, I could not reproduce this issue with iBridges under Linux.

**Comment by jpmcfarland** [comment]
So far while testing, I do not see the shift in levels, but a lack of uploading empty hidden directories. I am expanding my testing.

Also, hidden files/directories cannot be seen in the local tree view, so cannot be uploaded directly.  The iRODS tree view has no such problem.  I have made an issue for this (Issue #23).

**Comment by jpmcfarland** [comment]
Notice that in the first two figures above, the names of two folders are joined by a `\`, the folder delimiter in Windows, into one folder name in iRODS.  Also, in only the first figure above does the second folder begin with a `.`.  This denotes a hidden folder in POSIX operating systems (Linux, BSD, or Unix for instance).  I have checked with a folder hierarchy including both hidden and visible files and folders up to 4 levels.  I see no evidence of this issue so far:

![Screen Shot 2022-09-01 at 15 29 29](https://user-images.githubusercontent.com/13783312/187925998-7f1641cd-9091-439e-b925-492de9718def.png)

I cannot test with Windows, though I suspect it is a path handling issue specific to Windows due to the presence of the `\` delimiter.  There did not appear to be any consideration of differences in path handling between Windows paths and POSIX paths in the code, so this could easily be a result of that.  I have already updated the path handling in the upload and download algorithms used in the `Up and Download` view.

@PascaldeBoer Please try this operation again under Windows using the `develop` branch and report your results here.  In fact, everybody should be testing with the `develop` branch for the newest and most stable code.

**Comment by PascaldeBoer** [comment]
On windows, test environment RDMS, using the 34_fix_windows_issues branch:The same shuffling around of folder structure as described above happens with me if I upload folders with subfolders with `.` in the naming. However, I could work around it as well. I uploaded the folders as a zip and used to (un)bundle tab in the GUI to extract files. This worked out and resulted in collection with the normal, original subfolder structures. Of note, downloading these collections does not work again, I had to bundle them before again in order to download, bundling results in a tar by the way
