### ISSUE TITLE
Upload errors in 34_fix_windows_issues branch

### ISSUE THREAD

**Issue by PascaldeBoer** [rijksuniversiteit-groningen/iBridges-Gui#35]
Started using the 34_fix_windows_issues branch, since I could not login via windows under the develop branch.

Goal was to test whether abberant folder structures are fixed (issue #14) But I had errors with both uploading collections and single objects.

First tried the collections, to check whether issue #14 was solved. But had an error before upload could even starts, whereas I was able to upload whole collections before but with errors in the folder structure. The according error:
```

['varian_agilent\\quinine_PROTON_long_d1.fid\\test.fid', 'varian_agilent\\quinine_PROTON_long_d1.fid\\1D_imag', 'varian_agilent\\quinine_PROTON_long_d1.fid\\fid', 'varian_agilent\\quinine_PROTON_long_d1.fid\\1D_real', 'varian_agilent\\quinine_PROTON_long_d1.fid\\procpar', 'varian_agilent\\quinine_PROTON_long_d1.fid\\spectrum.dx', 'varian_agilent\\quinine_PROTON_long_d1.fid\\test.ft', 'varian_agilent\\quinine_PROTON_long_d1.fid\\1D_integ', 'varian_agilent\\quinine_PROTON_long_d1.fid\\peaks.txt', 'varian_agilent\\quinine_gHSQC.fid\\fid', 'varian_agilent\\quinine_gHSQC.fid\\procpar', 'varian_agilent\\quinine_PROTON_long_d1.fid\\test.csv', 'varian_agilent\\quinine_PROTON_long_d1.fid\\fid.com', 'varian_agilent\\quinine_gHSQC.fid\\text', 'varian_agilent\\quinine_PROTON_long_d1.fid\\text', 'varian_agilent\\quinine_PROTON_long_d1.fid\\log', 'varian_agilent\\quinine_gHSQC.fid\\log', 'varian_agilent\\quinine_PROTON_long_d1.fid\\start.py', 'varian_agilent\\quinine_PROTON_long_d1.fid\\1D_par', 'varian_agilent\\quinine_PROTON_long_d1.fid\\test.ft.csv'] 6129895
6129895 0
[2022-09-05 14:26:51,952] {IrodsConnector.py:827} INFO - iRODS UPLOAD: C:/Users/P265301/Documents/Data/Test_folder_hierarchy-->/testrug/home/pascal.de.boer@rug.nl/iBridges_test/20220905_test rootResc
[2022-09-05 14:26:51,955] {IrodsConnector.py:876} INFO - IRODS UPLOAD started:
[2022-09-05 14:26:51,981] {IrodsConnector.py:899} INFO - UPLOAD ERROR
Traceback (most recent call last):
  File "C:\Users\P265301\Documents\GitHub\iBridges\utils\IrodsConnector.py", line 893, in upload_data
    _ = self.ensure_coll(str(new_path))
  File "C:\Users\P265301\Documents\GitHub\iBridges\utils\IrodsConnector.py", line 427, in ensure_coll
    return self.session.collections.create(coll_name)
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\manager\collection_manager.py", line 35, in create
    response = conn.recv()
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\connection.py", line 106, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.SYS_INVALID_INPUT_PARAM: SYS_INVALID_INPUT_PARAM]  errno [] -- message [a valid zone name does not appear at the root of the object path [\testrug\home\pascal.de.boer@rug.nl\iBridges_test\20220905_test\Test_folder_hierarchy\varian_agilent\quinine_PROTON_long_d1.fid]]

[2022-09-05 14:26:51,981] {dataTransfer.py:260} INFO - SYS_INVALID_INPUT_PARAM('SYS_INVALID_INPUT_PARAM]  errno [] -- message [a valid zone name does not appear at the root of the object path [\\testrug\\home\\pascal.de.boer@rug.nl\\iBridges_test\\20220905_test\\Test_folder_hierarchy\\varian_agilent\\quinine_PROTON_long_d1.fid]]\n')
```
Then I wanted to test if this was a specific error for collections, resulting from `.` in the folder name or a more general issue. Therefore I uploaded a small single file. Also this resulted in an error:

```
[2022-09-05 14:41:21,539] {connection.py:443} INFO - PAM authorization validated
[2022-09-05 14:41:23,997] {IrodsConnector.py:369} INFO - GET PERMISSIONS
NoneType: None
[] 0
['C:/Users/P265301/Documents/Data/211220_smURFP/21-466_293T_1226_+Os_5.czi'] 2160672
2160672 0
[2022-09-05 14:41:30,913] {IrodsConnector.py:827} INFO - iRODS UPLOAD: C:/Users/P265301/Documents/Data/211220_smURFP/21-466_293T_1226_+Os_5.czi-->/testrug/home/pascal.de.boer@rug.nl/iBridges_test/20220905_test rootResc
[2022-09-05 14:41:30,915] {IrodsConnector.py:871} INFO - IRODS UPLOADING file C:\Users\P265301\Documents\Data\211220_smURFP\21-466_293T_1226_+Os_5.czi to \testrug\home\pascal.de.boer@rug.nl\iBridges_test\20220905_test\21-466_293T_1226_+Os_5.czi
[2022-09-05 14:41:30,945] {IrodsConnector.py:899} INFO - UPLOAD ERROR
Traceback (most recent call last):
  File "C:\Users\P265301\Documents\GitHub\iBridges\utils\IrodsConnector.py", line 873, in upload_data
    self.irods_put(str(src_path), str(dst_path), **options)
  File "C:\Users\P265301\Documents\GitHub\iBridges\utils\IrodsConnector.py", line 724, in irods_put
    self.session.data_objects.put(local_path, irods_path, **options)
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\manager\data_object_manager.py", line 111, in put
    with open(local_path, 'rb') as f, self.open(obj, 'w', **options) as o:
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\manager\data_object_manager.py", line 252, in open
    desc = conn.recv().int_info
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\connection.py", line 106, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.CAT_UNKNOWN_COLLECTION: collection '' is unknown
[2022-09-05 14:41:30,946] {dataTransfer.py:260} INFO - CAT_UNKNOWN_COLLECTION("collection '' is unknown")
```

**Comment by PascaldeBoer** [comment]
All the upload errors have been solved for me, see comment below issue [44](https://github.com/rijksuniversiteit-groningen/iBridges/issues/44).
