### ISSUE TITLE
Windows issues with jpm/feature/34_fix_windows_issues

### ISSUE THREAD

**Issue by PascaldeBoer** [rijksuniversiteit-groningen/iBridges-Gui#44]
I am using the branch with the newest commits (#34). I was not able to transfer data, both upload and download. I also tried both on the test and production server. Furthermore, I encountered error with browsing in the GUI under the browse tab. This was caused by the fact that the upon browsing the irods path changed from `/` to backslashes `\`, therefore it gave the error that the collection did not exist. Manually changing the slashes in the paths could solve it. 

**These are the errors for transfers:**

Upload error on test
```
['C:/Users/P265301/Documents/Data/Test.txt'] 9
9 0
[2022-10-12 10:53:19,404] {IrodsConnector.py:912} INFO - iRODS UPLOAD: C:/Users/P265301/Documents/Data/Test.txt-->/testrug/home/pascal.de.boer@rug.nl/iBridges_test/20221012_test rootResc / 27951
[2022-10-12 10:53:19,406] {dataTransfer.py:261} INFO - KeyError('rootResc / 27951')
Thread stopped
```

Download error on test
```
9 0
[2022-10-12 11:05:02,031] {dataTransfer.py:256} INFO - UpDownload Diff: ([], [], ['/testrug/home/pascal.de.boer@rug.nl/iBridges_test/Test.txt'], [])
[2022-10-12 11:05:02,033] {IrodsConnector.py:1011} INFO - iRODS DOWNLOAD: /testrug/home/pascal.de.boer@rug.nl/iBridges_test/Test.txt-->C:/Users/P265301/Documents/Downloads
[2022-10-12 11:05:02,036] {IrodsConnector.py:1060} INFO - IRODS DOWNLOADING object: /testrug/home/pascal.de.boer@rug.nl/iBridges_test/Test.txt to C:\Users\P265301\Documents\Downloads
[2022-10-12 11:05:02,046] {IrodsConnector.py:1088} INFO - DOWNLOAD ERROR
Traceback (most recent call last):
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\manager\collection_manager.py", line 17, in get
    result = query.one()
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\query.py", line 224, in one
    raise NoResultFound()
irods.exception.NoResultFound

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\P265301\Documents\GitHub\iBridges\utils\IrodsConnector.py", line 1063, in download_data
    self.irods_get(
  File "C:\Users\P265301\Documents\GitHub\iBridges\utils\IrodsConnector.py", line 825, in irods_get
    self.session.data_objects.get(irods_path, local_path, **options)
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\manager\data_object_manager.py", line 87, in get
    parent = self.sess.collections.get(irods_dirname(path))
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\manager\collection_manager.py", line 19, in get
    raise CollectionDoesNotExist()
irods.exception.CollectionDoesNotExist
[2022-10-12 11:05:02,053] {dataTransfer.py:261} INFO - CollectionDoesNotExist()
Thread stopped
```
Upload error on production

```
[] 0
['C:/Users/P265301/Documents/Data/Test.txt'] 9
9 0
[2022-10-12 10:47:11,048] {IrodsConnector.py:912} INFO - iRODS UPLOAD: C:/Users/P265301/Documents/Data/Test.txt-->/rug/home/pascal.de.boer@rug.nl/iBridges_Test/20221012 rootResc / 155562
[2022-10-12 10:47:11,049] {dataTransfer.py:261} INFO - KeyError('rootResc / 155562')
Thread stopped
```
Download error on production

```
[2022-10-12 10:47:46,874] {IrodsConnector.py:435} INFO - GET PERMISSIONS
NoneType: None
19 0
[2022-10-12 10:47:52,750] {dataTransfer.py:256} INFO - UpDownload Diff: ([], [], ['/rug/home/pascal.de.boer@rug.nl/test.txt'], [])
[2022-10-12 10:47:52,751] {IrodsConnector.py:1011} INFO - iRODS DOWNLOAD: /rug/home/pascal.de.boer@rug.nl/test.txt-->C:/Users/P265301/Documents/Downloads
[2022-10-12 10:47:52,757] {IrodsConnector.py:1060} INFO - IRODS DOWNLOADING object: /rug/home/pascal.de.boer@rug.nl/test.txt to C:\Users\P265301\Documents\Downloads
[2022-10-12 10:47:52,763] {IrodsConnector.py:1088} INFO - DOWNLOAD ERROR
Traceback (most recent call last):
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\manager\collection_manager.py", line 17, in get
    result = query.one()
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\query.py", line 224, in one
    raise NoResultFound()
irods.exception.NoResultFound

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\P265301\Documents\GitHub\iBridges\utils\IrodsConnector.py", line 1063, in download_data
    self.irods_get(
  File "C:\Users\P265301\Documents\GitHub\iBridges\utils\IrodsConnector.py", line 825, in irods_get
    self.session.data_objects.get(irods_path, local_path, **options)
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\manager\data_object_manager.py", line 87, in get
    parent = self.sess.collections.get(irods_dirname(path))
  File "C:\Users\P265301\AppData\Local\Programs\Python\Python39\lib\site-packages\irods\manager\collection_manager.py", line 19, in get
    raise CollectionDoesNotExist()
irods.exception.CollectionDoesNotExist
[2022-10-12 10:47:52,769] {dataTransfer.py:261} INFO - CollectionDoesNotExist()
Thread stopped
```

**Comment by jpmcfarland** [comment]
Okay, the upload error is an easy fix.  It is cause simply by forgetting an update.  The download problem is an issue with the Python iRODS client on Windows only.  The path separators are being swapped for an unknown reason.  This is the main trouble I had yesterday.  Unfortunately, I have no idea how long it will take to fix.  I should be able to have a work-around in place fairly quickly, however.

**Comment by PascaldeBoer** [comment]
I thouroughly tested on the test environment. I have now been able to transfer single files up to 11 GB both upload and download, the same goes for folders of the same size. Folders with tens of GBs size do not work, I received a "not enough space on resource" error. 

The path separators are now fine, I can normally browse through the client
