### ISSUE TITLE
Fix  "Could not receive server response" message when transferring bigger files

### ISSUE THREAD

**Issue by jnimoth** [rijksuniversiteit-groningen/iBridges-Gui#8]
I experiences an issue when trying to upload a big file (46 GB tar archive in this case).
The upload was performed in total three times. Every time, the progress window of the iBridges client displayed a "Could not receive server response" message. In my trials, this happens roughly 12 minutes after the transfer started. This is also visible in the command line entries of these files transfer.

![image](https://user-images.githubusercontent.com/109157914/179706946-9504fe72-108b-46b2-8dce-0ca194b43880.png)

1. Trial
```
['/mnt/c/Users/EWPuser/Downloads/RDMS_Bigger_Testfiles/RDMS_Bigger_Testfiles.tar'] 46430323200
46430323200 0
[2022-07-18 13:56:09,200] {irodsConnector.py:331} INFO - iRODS UPLOAD: /mnt/c/Users/EWPuser/Downloads/RDMS_Bigger_Testfiles/RDMS_Bigger_Testfiles.tar--><iRODSCollection 71618702 b'iBridges_Tests'>, rootRe
IRODS UPLOADING FILE /rug/home/[j.p.nimoth@rug.nl](mailto:j.p.nimoth@rug.nl)/iBridges_Tests/RDMS_Bigger_Testfiles.tar
[2022-07-18 13:56:14,716] {connection.py:443} INFO - PAM authorization validated
[2022-07-18 13:56:14,771] {parallel.py:307} INFO - num_threads = 4 ; (P)artitionSize = 11607580801
[2022-07-18 13:56:19,835] {connection.py:443} INFO - PAM authorization validated
[2022-07-18 13:56:24,998] {connection.py:443} INFO - PAM authorization validated
[2022-07-18 14:06:42,442] {connection.py:98} ERROR - Could not receive server response
[2022-07-18 14:08:42,543] {connection.py:98} ERROR - Could not receive server response
[2022-07-18 14:08:42,544] {dataTransfer.py:260} INFO - NetworkException('Could not receive server response')
```

2. Trial
```
['/mnt/c/Users/EWPuser/Downloads/RDMS_Bigger_Testfiles/RDMS_Bigger_Testfiles.tar'] 46430323200
46430323200 0
[2022-07-18 14:27:13,784] {irodsConnector.py:331} INFO - iRODS UPLOAD: /mnt/c/Users/EWPuser/Downloads/RDMS_Bigger_Testfiles/RDMS_Bigger_Testfiles.tar--><iRODSCollection 71618702 b'iBridges_Tests'>, rootResc
IRODS UPLOADING FILE /rug/home/[j.p.nimoth@rug.nl](mailto:j.p.nimoth@rug.nl)/iBridges_Tests/RDMS_Bigger_Testfiles.tar
[2022-07-18 14:27:15,005] {parallel.py:307} INFO - num_threads = 4 ; (P)artitionSize = 11607580801
[2022-07-18 14:27:20,732] {connection.py:443} INFO - PAM authorization validated
[2022-07-18 14:27:25,776] {connection.py:443} INFO - PAM authorization validated
[2022-07-18 14:37:27,799] {connection.py:98} ERROR - Could not receive server response
[2022-07-18 14:39:27,819] {connection.py:98} ERROR - Could not receive server response
[2022-07-18 14:39:27,820] {dataTransfer.py:260} INFO - NetworkException('Could not receive server response')
```

3. Trial
```
['/mnt/c/Users/EWPuser/Downloads/RDMS_Bigger_Testfiles/RDMS_Bigger_Testfiles.tar'] 46430323200
46430323200 0
[2022-07-18 15:16:56,470] {irodsConnector.py:331} INFO - iRODS UPLOAD: /mnt/c/Users/EWPuser/Downloads/RDMS_Bigger_Testfiles/RDMS_Bigger_Testfiles.tar--><iRODSCollection 71618702 b'iBridges_Tests'>, rootResc
IRODS UPLOADING FILE /rug/home/[j.p.nimoth@rug.nl](mailto:j.p.nimoth@rug.nl)/iBridges_Tests/RDMS_Bigger_Testfiles.tar
[2022-07-18 15:16:57,543] {parallel.py:307} INFO - num_threads = 4 ; (P)artitionSize = 11607580801
[2022-07-18 15:17:03,133] {connection.py:443} INFO - PAM authorization validated
[2022-07-18 15:27:32,172] {connection.py:98} ERROR - Could not receive server response
[2022-07-18 15:29:32,179] {connection.py:98} ERROR - Could not receive server response
[2022-07-18 15:29:32,179] {dataTransfer.py:260} INFO - NetworkException('Could not receive server response')
```

In all three cases, after roughly 10 minutes a `{connection.py:98} ERROR - Could not receive server response message` is displayed and shortly after that a `{dataTransfer.py:260} INFO - NetworkException('Could not receive server response')` message.

While a error messages are displayed in the GUI and command line, the file transfer seems to work without a problem:

```
jelte@WKS011378:~$ ils -L
/rug/home/[j.p.nimoth@rug.nl](mailto:j.p.nimoth@rug.nl)/iBridges_Tests:
 j.p.nimoth@r     0 rootResc;rootRandy;ptA;replA;randy01;pt002;mnt_irods002 46430323200 2022-07-18.15:17 & RDMS_Bigger_Testfiles.tar
   sha2:uFvDYHzFGsBIY9e+JC7hlM6Yq6MryliOTqzCT2MW/rg=   generic   /mnt/irods002/home/[j.p.nimoth@rug.nl](mailto:j.p.nimoth@rug.nl)/iBridges_Tests/RDMS_Bigger_Testfiles.tar
 j.p.nimoth@r     1 rootResc;rootRandy;ptA;replA;randy10;pt112;mnt_irods112 46430323200 2022-07-18.15:34 & RDMS_Bigger_Testfiles.tar
   sha2:uFvDYHzFGsBIY9e+JC7hlM6Yq6MryliOTqzCT2MW/rg=   generic   /mnt/irods112/home/[j.p.nimoth@rug.nl](mailto:j.p.nimoth@rug.nl)/iBridges_Tests/RDMS_Bigger_Testfiles.tar
```

I also compared the checksum of my local, original file that I used for testing with the checksum value that is marked in iRODS, both are identical:

```
jelte@WKS011378:~$ sha256sum /mnt/c/Users/EWPuser/Downloads/RDMS_Bigger_Testfiles/RDMS_Bigger_Testfiles.tar
b85bc3607cc51ac04863d7be242ee194ce98aba32bca588e4eacc24f6316feb8 /mnt/c/Users/EWPuser/Downloads/RDMS_Bigger_Testfiles/RDMS_Bigger_Testfiles.tar
jelte@WKS011378:~$ echo b85bc3607cc51ac04863d7be242ee194ce98aba32bca588e4eacc24f6316feb8 | xxd -r -p |base64
uFvDYHzFGsBIY9e+JC7hlM6Yq6MryliOTqzCT2MW/rg=
```

**Comment by jpmcfarland** [comment]
I have replicated this issue.  I believe this is more a file size issue than a transfer time issue.  During a transfer of only a 10GB file at max 3.3Gb/s, this error was seen.  It seems like it could be a bug in the iRODS Python client:

```python
Traceback (most recent call last):
  File "/home/p236378/.local/lib/python3.9/site-packages/irods/message/__init__.py", line 30, in _recv_message_in_len
    buf = sock.recv(size_left, socket.MSG_WAITALL)
  File "/software/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/ssl.py", line 1223, in recv
    raise ValueError(
ValueError: non-zero flags not allowed in calls to recv() on <class 'ssl.SSLSocket'>
```

I will try to reproduce it outside iBridges.

**Comment by jpmcfarland** [comment]
Despite the errors, the file is always correctly transferred.  Once there was a replication error, but that was on the iRODS side.  No telling what actually caused it.  Here is the likely error:

```
ERROR: rsDataObjClose: dataObjInp for index 3 is null
```

**Comment by jpmcfarland** [comment]
Transferring larger files outside of **iBridges** with only the iRODS Python client results in the same error, but somewhat intermittently.  I will try to optimize the transfer with options.  if this does not help, I will report a bug of the iRODS Python client.

**Comment by jpmcfarland** [comment]
Reported the issue in the Python iRODS Client (PRC): https://github.com/irods/python-irodsclient/issues/377
